version: "3.8"

services:
  sushi:
    build: .
    container_name: sushi
    volumes:
      - ./:/code
    devices:
      - /dev/snd:/dev/snd # enable sound
    command: /root/sequensual/bin/sequencer
    group_add:
      - audio
