version: "3.8"

services:
  sushi:
    build: .
    container_name: sushi
    volumes:
      - ./:/code
      - ./config/asound.conf:/etc/asound.conf
      - ./config/limits.conf:/etc/security/limits.conf
    devices:
      - /dev/snd:/dev/snd # enable sound
    command: /root/sequensual/bin/sequencer
    group_add:
      - audio
    privileged: true
